### PR TITLE
Update Unites States holidays: remove Columbus Day from countrywide holidays

### LINKED ISSUE #2103: Columbus Day is not observed in all states
### Expected Behavior

**Columbus Day** is a federal holiday that's not observed in many US states (e.g. California).

```python
>>> holidays.US(years=2024, subdiv="CA").get(date(2024, 10, 14))
>>>
```

So I believe it shouldn't be returned if `subdiv` is not provided?

```python
>>> holidays.US(years=2024).get(date(2024, 10, 14))
>>>
```

### Actual Behavior

```python
>>> holidays.US(years=2024).get(date(2024, 10, 14))
'Columbus Day'
>>>
```

### Steps to Reproduce the Problem

  1. `>>> import holidays`
  2. `>>> from datetime import date`
  3. `>>> holidays.US(years=2024).get(date(2024, 10, 14))`

### Environment

- OS: macOS 13.5
- Python version: 3.12.5
- holidays version: 0.59

### Additional Context

Perhaps I misunderstood something, shouldn't country holidays calls `holidays.US(years=2024)` return **_nationwide_** holidays? That apply to all subdivisions?

### PR DESCRIPTION
**Pull request by KJhellico**
## Proposed change

Update Unites States holidays: remove Columbus Day from countrywide holidays.
Resolves #2103.

## Type of change

- [ ] New country/market holidays support (thank you!)
- [x] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/pin/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new `holidays` functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've successfully run `make check`, all checks and tests are green

[contributing-guidelines]: https://github.com/vacanza/holidays/blob/dev/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/holidays/tree/dev/docs/source

### CODE REVIEW

**Comment by PPsyrius** [comment]
Since "Columbus Day" is still observed by [Federal Government offices](https://www.abc10.com/article/news/local/california/columbus-day-open-costco-schools-banks-dmv/103-194f310e-83b4-4728-a4fc-b4e3cca4880a) and the [US Postal Service](https://about.usps.com/newsroom/local-releases/ca/2024/1001-usps-schedule-for-columbus-day.htm) even in states that don't observe this i.e. California - I think they should be moved to `GOVERNMENT` category instead IMO.

**Comment by KJhellico** [comment]
I think we need to implement **all** federal holidays as `GOVERNMENT` later. And in general, to review US holidays completely...

**Review by PPsyrius — APPROVED** [review]
Ok, let's do a full review of the US holidays later.

LGTM for the current Columbus Day changes 🇺🇸

**Review by arkid15r — COMMENTED** [review]
😵 LGTM

**Pull request merged**
