### PR TITLE
Update Germany holidays: add Liberation from Nazi Regime Day 2025 in Berlin

### LINKED ISSUE #2051: Missing "Tag der Befreiung" 2025-05-08:  One-Time Holiday in Berlin, Germany (DE-BE)
## Bug Report

The public holiday 'Tag der Befreiung' on 2025-05-08 is missing in Berlin, Germany.

### Expected Behavior

I expect it to be present, because it's a public holiday.

### Actual Behavior

It's not included in the library.

Source: https://www.berlin.de/aktuelles/9188766-958090-einmaliger-feiertag-am-8-mai-2025.html

### PR DESCRIPTION
**Pull request by hf-kklein**
source: https://www.berlin.de/aktuelles/9188766-958090-einmaliger-feiertag-am-8-mai-2025.html

fixes #2051

Sorry, didn't get my setup ready to generate the snapshots.

### CODE REVIEW

**Comment by KJhellico** [comment]
@hf-kklein, thank you for your contribution! However, we implement such one-time holidays as “special holidays” (see [similar holiday in 2020](https://github.com/vacanza/holidays/blob/ebe2ca086d27108b8662060b1894875f5f43c9c8/holidays/countries/germany.py#L312)).

**Comment by PPsyrius** [comment]
@hf-kklein Check your git repo, I've created a PR that addresses all the issues above as well as adding translations, test cases, and updated snapshots. 🙏 

@arkid15r @KJhellico We should probably add a new entry for `may_8` victory day in the `international` holiday group as they're currently in use by France, Poland, Czechia, Slovakia, and Ukraine.

I'm not sure if I can come up with a name for it though - USSR-derived ones that are celebrated on May 9th currently use `_add_world_war_two_victory_day` at the moment

**Comment by PPsyrius** [comment]
@hf-kklein Don't forget to add your name to the [AUTHORS](https://github.com/vacanza/holidays/blob/dev/AUTHORS) file as well :)

**Review by KJhellico — APPROVED** [review]
LGTM 👍

**Review by arkid15r — COMMENTED** [review]
Thanks for the contribution @hf-kklein!

**Comment by arkid15r** [comment]
> after the merge, a version bump would be highly appreciated :)

If you mean releasing the new version -- it's going to be the next Mon, Oct 21st.

**Comment by PPsyrius** [comment]
@hf-kklein You might want to increase the minimum python version as well since we dropped 3.8 support in 0.59.

**Pull request merged**
